"""pokemon

Revision ID: 6fb4ebf78e5a
Revises: 9ba5b15f552e
Create Date: 2023-03-07 23:51:27.143940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb4ebf78e5a'
down_revision = '9ba5b15f552e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('vida', sa.String(length=80), nullable=True),
    sa.Column('ataque', sa.String(length=80), nullable=True),
    sa.Column('defensa', sa.String(length=80), nullable=True),
    sa.Column('especialidad', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
