"""add pokemons foto

Revision ID: 91780a466256
Revises: 6fb4ebf78e5a
Create Date: 2023-03-08 21:38:29.835477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91780a466256'
down_revision = '6fb4ebf78e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
