"""usuario

Revision ID: 9ba5b15f552e
Revises: 585c8e4ade0f
Create Date: 2023-03-07 20:24:33.282861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba5b15f552e'
down_revision = '585c8e4ade0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=True),
    sa.Column('correo', sa.String(length=80), nullable=True),
    sa.Column('contrasena', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
